// Code generated by acme-manager, DO NOT EDIT.
// Code from https://github.com/go-acme/lego/tree/v4.19.2/providers/dns/iijdpf
// License: MIT

package iijdpf

import (
	"acme-manager/acme/lego"
	"acme-manager/logger"
	"fmt"
	"strings"
	"time"

	mapset "github.com/deckarep/golang-set/v2"
	"github.com/go-acme/lego/v4/providers/dns/iijdpf"
	dpfapi "github.com/mimuret/golang-iij-dpf/pkg/api"
	"github.com/santhosh-tekuri/jsonschema/v6"
)

const (
	EnvAPIEndpoint        = "apiEndpoint"
	EnvAPIToken           = "apiToken"
	EnvPollingInterval    = "pollingInterval"
	EnvPropagationTimeout = "propagationTimeout"
	EnvServiceCode        = "dpmServiceCode"
	EnvTTL                = "ttl"
)

const JsonSchema = "{\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"title\":\"IIJ DNS Platform Service Configuration\",\"type\":\"object\",\"properties\":{\"credentials\":{\"apiToken\":{\"type\":\"string\",\"description\":\"API token\"},\"dpmServiceCode\":{\"type\":\"string\",\"description\":\"IIJ Managed DNS Service's service code\"}},\"additional\":{\"apiEndpoint\":{\"type\":\"string\",\"description\":\"API endpoint URL, defaults to https://api.dns-platform.jp/dpf/v1\"},\"pollingInterval\":{\"type\":\"string\",\"description\":\"Time between DNS propagation check, defaults to 5 second\"},\"propagationTimeout\":{\"type\":\"string\",\"description\":\"Maximum waiting time for DNS propagation, defaults to 660 second\"},\"ttl\":{\"type\":\"string\",\"description\":\"The TTL of the TXT record used for the DNS challenge, default to 300\"}}}}"

var compiledJsonSchema *jsonschema.Schema

var credentialsFields = mapset.NewSet("apiToken", "dpmServiceCode")
var additionalFields = mapset.NewSet("apiEndpoint", "pollingInterval", "propagationTimeout", "ttl")

func init() {
	schema, err := jsonschema.UnmarshalJSON(strings.NewReader(JsonSchema))
	if err != nil {
		logger.Fatalf("Failed to unmarshal iijdpf JSON schema: %v", err)
	}
	compiler := jsonschema.NewCompiler()
	if err := compiler.AddResource("schema.json", schema); err != nil {
		logger.Fatalf("Failed to add iijdpf schema resource to compiler: %v", err)
	}
	compiledJsonSchema, err = compiler.Compile("schema.json")
	if err != nil {
		logger.Fatalf("Failed to compile iijdpf schema: %v", err)
	}
}

func ParseConfig(conf *lego.DnsProviderConfig) (*lego.Env, error) {
	data := make(map[string]string)
	if conf.Credentials != nil {
		for key, value := range conf.Credentials {
			if credentialsFields.Contains(key) {
				data[key] = value
			} else {
				delete(conf.Credentials, key)
			}
		}
	}
	if conf.Additional != nil {
		for key, value := range conf.Additional {
			if additionalFields.Contains(key) {
				data[key] = value
			} else {
				delete(conf.Additional, key)
			}
		}
	}

	anyData := make(map[string]any)
	for key, value := range data {
		anyData[key] = value
	}
	if err := compiledJsonSchema.Validate(anyData); err != nil {
		return nil, fmt.Errorf("iijdpf: configuration validation failed: %v", err)
	}

	env := lego.NewEnv(data)
	return &env, nil
}

func NewConfig(env lego.Env) *iijdpf.Config {
	return &iijdpf.Config{
		Endpoint:           env.GetOrDefaultString(EnvAPIEndpoint, dpfapi.DefaultEndpoint),
		PropagationTimeout: env.GetOrDefaultSecond(EnvPropagationTimeout, 660*time.Second),
		PollingInterval:    env.GetOrDefaultSecond(EnvPollingInterval, 5*time.Second),
		TTL:                env.GetOrDefaultInt(EnvTTL, 300),
	}
}

func NewDNSProvider(env lego.Env) (*iijdpf.DNSProvider, error) {
	values, err := env.Get(EnvAPIToken, EnvServiceCode)
	if err != nil {
		return nil, fmt.Errorf("iijdpf: %w", err)
	}

	config := NewConfig(env)
	config.Token = values[EnvAPIToken]
	config.ServiceCode = values[EnvServiceCode]

	return iijdpf.NewDNSProviderConfig(config)
}
