// Code generated by acme-manager, DO NOT EDIT.
// Code from https://github.com/go-acme/lego/tree/v4.19.2/providers/dns/nicmanager
// License: MIT

package nicmanager

import (
	"acme-manager/acme/lego"
	"acme-manager/logger"
	"fmt"
	"net/http"
	"strings"
	"time"

	mapset "github.com/deckarep/golang-set/v2"
	"github.com/go-acme/lego/v4/challenge/dns01"
	"github.com/go-acme/lego/v4/providers/dns/nicmanager"
	"github.com/santhosh-tekuri/jsonschema/v6"
)

const (
	EnvEmail              = "apiEmail"
	EnvHTTPTimeout        = "httpTimeout"
	EnvLogin              = "apiLogin"
	EnvMode               = "mode"
	EnvOTP                = "apiOtp"
	EnvPassword           = "apiPassword"
	EnvPollingInterval    = "pollingInterval"
	EnvPropagationTimeout = "propagationTimeout"
	EnvTTL                = "ttl"
	EnvUsername           = "apiUsername"
	minTTL                = 900
)

const JsonSchema = "{\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"title\":\"Nicmanager Configuration\",\"type\":\"object\",\"properties\":{\"credentials\":{\"apiLogin\":{\"type\":\"string\",\"description\":\"Login, used for Username-based login\"},\"apiUsername\":{\"type\":\"string\",\"description\":\"Username, used for Username-based login\"},\"apiEmail\":{\"type\":\"string\",\"description\":\"Email-based login\"},\"apiPassword\":{\"type\":\"string\",\"description\":\"Password, always required\"}},\"additional\":{\"mode\":{\"type\":\"string\"},\"apiOtp\":{\"type\":\"string\",\"description\":\"TOTP Secret (optional)\"},\"apiMode\":{\"type\":\"string\",\"description\":\"mode: 'anycast' or 'zone' (default: 'anycast')\"},\"pollingInterval\":{\"type\":\"string\",\"description\":\"Time between DNS propagation check\"},\"propagationTimeout\":{\"type\":\"string\",\"description\":\"Maximum waiting time for DNS propagation\"},\"ttl\":{\"type\":\"string\",\"description\":\"The TTL of the TXT record used for the DNS challenge\"},\"httpTimeout\":{\"type\":\"string\",\"description\":\"API request timeout\"}}}}"

var compiledJsonSchema *jsonschema.Schema

var credentialsFields = mapset.NewSet("apiLogin", "apiUsername", "apiEmail", "apiPassword")
var additionalFields = mapset.NewSet("mode", "apiOtp", "apiMode", "pollingInterval", "propagationTimeout", "ttl", "httpTimeout")

func init() {
	schema, err := jsonschema.UnmarshalJSON(strings.NewReader(JsonSchema))
	if err != nil {
		logger.Fatalf("Failed to unmarshal nicmanager JSON schema: %v", err)
	}
	compiler := jsonschema.NewCompiler()
	if err := compiler.AddResource("schema.json", schema); err != nil {
		logger.Fatalf("Failed to add nicmanager schema resource to compiler: %v", err)
	}
	compiledJsonSchema, err = compiler.Compile("schema.json")
	if err != nil {
		logger.Fatalf("Failed to compile nicmanager schema: %v", err)
	}
}

func ParseConfig(conf *lego.DnsProviderConfig) (*lego.Env, error) {
	data := make(map[string]string)
	if conf.Credentials != nil {
		for key, value := range conf.Credentials {
			if credentialsFields.Contains(key) {
				data[key] = value
			} else {
				delete(conf.Credentials, key)
			}
		}
	}
	if conf.Additional != nil {
		for key, value := range conf.Additional {
			if additionalFields.Contains(key) {
				data[key] = value
			} else {
				delete(conf.Additional, key)
			}
		}
	}

	anyData := make(map[string]any)
	for key, value := range data {
		anyData[key] = value
	}
	if err := compiledJsonSchema.Validate(anyData); err != nil {
		return nil, fmt.Errorf("nicmanager: configuration validation failed: %v", err)
	}

	env := lego.NewEnv(data)
	return &env, nil
}

func NewConfig(env lego.Env) *nicmanager.Config {
	return &nicmanager.Config{
		TTL:                env.GetOrDefaultInt(EnvTTL, minTTL),
		PropagationTimeout: env.GetOrDefaultSecond(EnvPropagationTimeout, 5*time.Minute),
		PollingInterval:    env.GetOrDefaultSecond(EnvPollingInterval, dns01.DefaultPollingInterval),
		HTTPClient: &http.Client{
			Timeout: env.GetOrDefaultSecond(EnvHTTPTimeout, 10*time.Second),
		},
	}
}

func NewDNSProvider(env lego.Env) (*nicmanager.DNSProvider, error) {
	values, err := env.Get(EnvPassword)
	if err != nil {
		return nil, fmt.Errorf("nicmanager: %w", err)
	}

	config := NewConfig(env)
	config.Password = values[EnvPassword]

	config.Mode = env.GetOrDefaultString(EnvMode, ModeAnycast)
	config.Username = env.GetOrFile(EnvUsername)
	config.Login = env.GetOrFile(EnvLogin)
	config.Email = env.GetOrFile(EnvEmail)
	config.OTPSecret = env.GetOrFile(EnvOTP)

	if config.TTL < minTTL {
		return nil, fmt.Errorf("TTL must be higher than %d: %d", minTTL, config.TTL)
	}

	return nicmanager.NewDNSProviderConfig(config)
}
