// Code generated by ent, DO NOT EDIT.

package ent

import (
	"acme-manager/ent/acmeaccount"
	"acme-manager/ent/acmeserver"
	"acme-manager/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AcmeServerQuery is the builder for querying AcmeServer entities.
type AcmeServerQuery struct {
	config
	ctx                   *QueryContext
	order                 []acmeserver.OrderOption
	inters                []Interceptor
	predicates            []predicate.AcmeServer
	withAcmeAccounts      *AcmeAccountQuery
	modifiers             []func(*sql.Selector)
	loadTotal             []func(context.Context, []*AcmeServer) error
	withNamedAcmeAccounts map[string]*AcmeAccountQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AcmeServerQuery builder.
func (asq *AcmeServerQuery) Where(ps ...predicate.AcmeServer) *AcmeServerQuery {
	asq.predicates = append(asq.predicates, ps...)
	return asq
}

// Limit the number of records to be returned by this query.
func (asq *AcmeServerQuery) Limit(limit int) *AcmeServerQuery {
	asq.ctx.Limit = &limit
	return asq
}

// Offset to start from.
func (asq *AcmeServerQuery) Offset(offset int) *AcmeServerQuery {
	asq.ctx.Offset = &offset
	return asq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (asq *AcmeServerQuery) Unique(unique bool) *AcmeServerQuery {
	asq.ctx.Unique = &unique
	return asq
}

// Order specifies how the records should be ordered.
func (asq *AcmeServerQuery) Order(o ...acmeserver.OrderOption) *AcmeServerQuery {
	asq.order = append(asq.order, o...)
	return asq
}

// QueryAcmeAccounts chains the current query on the "acme_accounts" edge.
func (asq *AcmeServerQuery) QueryAcmeAccounts() *AcmeAccountQuery {
	query := (&AcmeAccountClient{config: asq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := asq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := asq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(acmeserver.Table, acmeserver.FieldID, selector),
			sqlgraph.To(acmeaccount.Table, acmeaccount.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, acmeserver.AcmeAccountsTable, acmeserver.AcmeAccountsColumn),
		)
		fromU = sqlgraph.SetNeighbors(asq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AcmeServer entity from the query.
// Returns a *NotFoundError when no AcmeServer was found.
func (asq *AcmeServerQuery) First(ctx context.Context) (*AcmeServer, error) {
	nodes, err := asq.Limit(1).All(setContextOp(ctx, asq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{acmeserver.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (asq *AcmeServerQuery) FirstX(ctx context.Context) *AcmeServer {
	node, err := asq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AcmeServer ID from the query.
// Returns a *NotFoundError when no AcmeServer ID was found.
func (asq *AcmeServerQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = asq.Limit(1).IDs(setContextOp(ctx, asq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{acmeserver.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (asq *AcmeServerQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := asq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AcmeServer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AcmeServer entity is found.
// Returns a *NotFoundError when no AcmeServer entities are found.
func (asq *AcmeServerQuery) Only(ctx context.Context) (*AcmeServer, error) {
	nodes, err := asq.Limit(2).All(setContextOp(ctx, asq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{acmeserver.Label}
	default:
		return nil, &NotSingularError{acmeserver.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (asq *AcmeServerQuery) OnlyX(ctx context.Context) *AcmeServer {
	node, err := asq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AcmeServer ID in the query.
// Returns a *NotSingularError when more than one AcmeServer ID is found.
// Returns a *NotFoundError when no entities are found.
func (asq *AcmeServerQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = asq.Limit(2).IDs(setContextOp(ctx, asq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{acmeserver.Label}
	default:
		err = &NotSingularError{acmeserver.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (asq *AcmeServerQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := asq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AcmeServers.
func (asq *AcmeServerQuery) All(ctx context.Context) ([]*AcmeServer, error) {
	ctx = setContextOp(ctx, asq.ctx, ent.OpQueryAll)
	if err := asq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AcmeServer, *AcmeServerQuery]()
	return withInterceptors[[]*AcmeServer](ctx, asq, qr, asq.inters)
}

// AllX is like All, but panics if an error occurs.
func (asq *AcmeServerQuery) AllX(ctx context.Context) []*AcmeServer {
	nodes, err := asq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AcmeServer IDs.
func (asq *AcmeServerQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if asq.ctx.Unique == nil && asq.path != nil {
		asq.Unique(true)
	}
	ctx = setContextOp(ctx, asq.ctx, ent.OpQueryIDs)
	if err = asq.Select(acmeserver.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (asq *AcmeServerQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := asq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (asq *AcmeServerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, asq.ctx, ent.OpQueryCount)
	if err := asq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, asq, querierCount[*AcmeServerQuery](), asq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (asq *AcmeServerQuery) CountX(ctx context.Context) int {
	count, err := asq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (asq *AcmeServerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, asq.ctx, ent.OpQueryExist)
	switch _, err := asq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (asq *AcmeServerQuery) ExistX(ctx context.Context) bool {
	exist, err := asq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AcmeServerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (asq *AcmeServerQuery) Clone() *AcmeServerQuery {
	if asq == nil {
		return nil
	}
	return &AcmeServerQuery{
		config:           asq.config,
		ctx:              asq.ctx.Clone(),
		order:            append([]acmeserver.OrderOption{}, asq.order...),
		inters:           append([]Interceptor{}, asq.inters...),
		predicates:       append([]predicate.AcmeServer{}, asq.predicates...),
		withAcmeAccounts: asq.withAcmeAccounts.Clone(),
		// clone intermediate query.
		sql:  asq.sql.Clone(),
		path: asq.path,
	}
}

// WithAcmeAccounts tells the query-builder to eager-load the nodes that are connected to
// the "acme_accounts" edge. The optional arguments are used to configure the query builder of the edge.
func (asq *AcmeServerQuery) WithAcmeAccounts(opts ...func(*AcmeAccountQuery)) *AcmeServerQuery {
	query := (&AcmeAccountClient{config: asq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	asq.withAcmeAccounts = query
	return asq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AcmeServer.Query().
//		GroupBy(acmeserver.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (asq *AcmeServerQuery) GroupBy(field string, fields ...string) *AcmeServerGroupBy {
	asq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AcmeServerGroupBy{build: asq}
	grbuild.flds = &asq.ctx.Fields
	grbuild.label = acmeserver.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.AcmeServer.Query().
//		Select(acmeserver.FieldName).
//		Scan(ctx, &v)
func (asq *AcmeServerQuery) Select(fields ...string) *AcmeServerSelect {
	asq.ctx.Fields = append(asq.ctx.Fields, fields...)
	sbuild := &AcmeServerSelect{AcmeServerQuery: asq}
	sbuild.label = acmeserver.Label
	sbuild.flds, sbuild.scan = &asq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AcmeServerSelect configured with the given aggregations.
func (asq *AcmeServerQuery) Aggregate(fns ...AggregateFunc) *AcmeServerSelect {
	return asq.Select().Aggregate(fns...)
}

func (asq *AcmeServerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range asq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, asq); err != nil {
				return err
			}
		}
	}
	for _, f := range asq.ctx.Fields {
		if !acmeserver.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if asq.path != nil {
		prev, err := asq.path(ctx)
		if err != nil {
			return err
		}
		asq.sql = prev
	}
	return nil
}

func (asq *AcmeServerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AcmeServer, error) {
	var (
		nodes       = []*AcmeServer{}
		_spec       = asq.querySpec()
		loadedTypes = [1]bool{
			asq.withAcmeAccounts != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AcmeServer).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AcmeServer{config: asq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(asq.modifiers) > 0 {
		_spec.Modifiers = asq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, asq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := asq.withAcmeAccounts; query != nil {
		if err := asq.loadAcmeAccounts(ctx, query, nodes,
			func(n *AcmeServer) { n.Edges.AcmeAccounts = []*AcmeAccount{} },
			func(n *AcmeServer, e *AcmeAccount) { n.Edges.AcmeAccounts = append(n.Edges.AcmeAccounts, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range asq.withNamedAcmeAccounts {
		if err := asq.loadAcmeAccounts(ctx, query, nodes,
			func(n *AcmeServer) { n.appendNamedAcmeAccounts(name) },
			func(n *AcmeServer, e *AcmeAccount) { n.appendNamedAcmeAccounts(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range asq.loadTotal {
		if err := asq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (asq *AcmeServerQuery) loadAcmeAccounts(ctx context.Context, query *AcmeAccountQuery, nodes []*AcmeServer, init func(*AcmeServer), assign func(*AcmeServer, *AcmeAccount)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*AcmeServer)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(acmeaccount.FieldAcmeServerID)
	}
	query.Where(predicate.AcmeAccount(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(acmeserver.AcmeAccountsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AcmeServerID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "acme_server_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (asq *AcmeServerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := asq.querySpec()
	if len(asq.modifiers) > 0 {
		_spec.Modifiers = asq.modifiers
	}
	_spec.Node.Columns = asq.ctx.Fields
	if len(asq.ctx.Fields) > 0 {
		_spec.Unique = asq.ctx.Unique != nil && *asq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, asq.driver, _spec)
}

func (asq *AcmeServerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(acmeserver.Table, acmeserver.Columns, sqlgraph.NewFieldSpec(acmeserver.FieldID, field.TypeUUID))
	_spec.From = asq.sql
	if unique := asq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if asq.path != nil {
		_spec.Unique = true
	}
	if fields := asq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, acmeserver.FieldID)
		for i := range fields {
			if fields[i] != acmeserver.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := asq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := asq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := asq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := asq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (asq *AcmeServerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(asq.driver.Dialect())
	t1 := builder.Table(acmeserver.Table)
	columns := asq.ctx.Fields
	if len(columns) == 0 {
		columns = acmeserver.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if asq.sql != nil {
		selector = asq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if asq.ctx.Unique != nil && *asq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range asq.predicates {
		p(selector)
	}
	for _, p := range asq.order {
		p(selector)
	}
	if offset := asq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := asq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedAcmeAccounts tells the query-builder to eager-load the nodes that are connected to the "acme_accounts"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (asq *AcmeServerQuery) WithNamedAcmeAccounts(name string, opts ...func(*AcmeAccountQuery)) *AcmeServerQuery {
	query := (&AcmeAccountClient{config: asq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if asq.withNamedAcmeAccounts == nil {
		asq.withNamedAcmeAccounts = make(map[string]*AcmeAccountQuery)
	}
	asq.withNamedAcmeAccounts[name] = query
	return asq
}

// AcmeServerGroupBy is the group-by builder for AcmeServer entities.
type AcmeServerGroupBy struct {
	selector
	build *AcmeServerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (asgb *AcmeServerGroupBy) Aggregate(fns ...AggregateFunc) *AcmeServerGroupBy {
	asgb.fns = append(asgb.fns, fns...)
	return asgb
}

// Scan applies the selector query and scans the result into the given value.
func (asgb *AcmeServerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, asgb.build.ctx, ent.OpQueryGroupBy)
	if err := asgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AcmeServerQuery, *AcmeServerGroupBy](ctx, asgb.build, asgb, asgb.build.inters, v)
}

func (asgb *AcmeServerGroupBy) sqlScan(ctx context.Context, root *AcmeServerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(asgb.fns))
	for _, fn := range asgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*asgb.flds)+len(asgb.fns))
		for _, f := range *asgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*asgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := asgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AcmeServerSelect is the builder for selecting fields of AcmeServer entities.
type AcmeServerSelect struct {
	*AcmeServerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ass *AcmeServerSelect) Aggregate(fns ...AggregateFunc) *AcmeServerSelect {
	ass.fns = append(ass.fns, fns...)
	return ass
}

// Scan applies the selector query and scans the result into the given value.
func (ass *AcmeServerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ass.ctx, ent.OpQuerySelect)
	if err := ass.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AcmeServerQuery, *AcmeServerSelect](ctx, ass.AcmeServerQuery, ass, ass.inters, v)
}

func (ass *AcmeServerSelect) sqlScan(ctx context.Context, root *AcmeServerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ass.fns))
	for _, fn := range ass.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ass.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ass.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
