// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
)

func (aa *AcmeAccount) AcmeServer(ctx context.Context) (*AcmeServer, error) {
	result, err := aa.Edges.AcmeServerOrErr()
	if IsNotLoaded(err) {
		result, err = aa.QueryAcmeServer().Only(ctx)
	}
	return result, err
}

func (c *Certificate) AcmeAccount(ctx context.Context) (*AcmeAccount, error) {
	result, err := c.Edges.AcmeAccountOrErr()
	if IsNotLoaded(err) {
		result, err = c.QueryAcmeAccount().Only(ctx)
	}
	return result, err
}

func (c *Certificate) DNSProvider(ctx context.Context) (*DnsProvider, error) {
	result, err := c.Edges.DNSProviderOrErr()
	if IsNotLoaded(err) {
		result, err = c.QueryDNSProvider().Only(ctx)
	}
	return result, err
}
