// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AcmeAccount is the predicate function for acmeaccount builders.
type AcmeAccount func(*sql.Selector)

// AcmeServer is the predicate function for acmeserver builders.
type AcmeServer func(*sql.Selector)

// Certificate is the predicate function for certificate builders.
type Certificate func(*sql.Selector)

// DnsProvider is the predicate function for dnsprovider builders.
type DnsProvider func(*sql.Selector)
